language: node_js
node_js:
  - 14
before_install:
  - npm i -g npm@7.6.0

install:
  - npm ci

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage